initial commit
mvg-internship/basicviz pull request #1
Opened 2022-12-25 12:32 UTC by yaksase

2022-12-26 11:53 UTC, greye requested changes
General notes:

- commits must contain meaningful messages related to the changes
- multiple small commits are better than a couple of large commits
- code formatting must be consistent

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +
Non-configurable Integer constants must be enumerations, e.g. 
```suggestion
enum {
    HSPACING = 2,
    VSPACING = 2
}
```

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +
Screen sizes widely varies and should be either set manually on launch or detected automatically.

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +};
Names starting with an underscore (_) are reserved in the language.
Moreover, do not use prefixes or suffixes for class member names: whenever (if ever) you need a distinction, you may use `this->memberName`

2022-12-26 11:53 UTC, greye commented on test/CMakeLists.txt
> +set(CMAKE_EXE_LINKER_FLAGS "-static")
What is the point of the flag? SDL2 forbids static linking (or at least requires intrusive changes to do so), lorina is a header-only library.

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +//Standard libs includes
Avoid obvious comments.

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +//External libs includes
Avoid obvious comments.

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +        _scheme.emplace_back(input);
The purpose of `emplace_back` is not clear: `emplace_back` should be used to *construct* an object *in-place*, otherwise use `push_back`. If you want to avoid a copy, use `push_back(std::move(input))`.

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +    std::vector< std::tuple< Vertex, std::vector< std::string > > > _queue;
Using a vector of vectors for dynamic structures, e.g. queues, is usually a bad call since it requires redundant copies on resize and removal.

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +        for(auto vert : _scheme) {
(here and later) By default auto means value-type (not reference-type), therefore every element is copied during iteration -- it is undesirable for nested data structures. Use reference specifier, e.g. `auto &vert: _scheme`.

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +    void output() {
Providing a method to print to stdout is ok, but it is better to generalize a bit, e.g. pass an output stream as a method parameter.

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +    bool check_inputs(Vertex& element, std::vector<std::string>& ins) {
The naming is ambiguous: what is the result of the check? Moreover, method body does something very different to just checking inputs.

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +    void request_handling() {
The naming is ambiguous: what does it mean to "request" handling?

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +        std::vector<std::string> ins = _inputs;
Unnecessary variable, redundant copy.

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +            rect.y = count * 2 * height;
"Magic" numbers (2 in this case) are not allowed in the source code. Use named constants in expressions or named functions to calculate the result.

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +            }
Pretty obvious code duplication.

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +        }
Pretty obvious code duplication.

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +            for(auto compared_element : layered_elements) {
Number of inputs is presumably small (up to 4, basically) while number of vertices is *much* larger: many searches in small collection is much better than searches in a large collection. Or just use a better data structure to quickly find all name references.

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +#define SDL_MAIN_HANDLED
Set the define close to the point where it is needed, i.e. `#include <SDL.h>`

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +                }
`Line`-related calculations are better to be corresponding methods of the `Line` class.

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +    if(argc != 2) return -1;
At least print the usage hints to the user.

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +    if(result != lorina::return_code::success) return -2;
Print an error message to notify the user what is wrong.

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +    logicScheme.output();
Comment does not fit the code. Like, what queue? How `request_hanling` or `output` should clear a queue?

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +    if(argc != 2) return -1;
Use an enumeration for error codes.

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +    if(result != lorina::return_code::success) return -2;
Use an enumeration for error codes.

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +    if(SDL_Init(SDL_INIT_VIDEO) < 0) return -3;
Use an enumeration for error codes.

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +
Do not mix SDL setup and placement logic: create corresponding procedures and keep them separate.

2022-12-26 11:53 UTC, greye commented on test/test-viz.cpp
> +
Create a separate rendering procedure for draw calls.

2022-12-30 23:23 UTC, greye requested changes

2022-12-30 23:23 UTC, greye commented on test/test-viz.cpp
> +enum SPACING {
Unconventional naming: UPPER_SNAKE_CASE is generally used for global constants or macros. Moreover, it is fine to not name a type at all when it's name is not referenced:
```suggestion
enum {
```

2022-12-30 23:23 UTC, greye commented on test/test-viz.cpp
> +enum ERROR_CODES {
Type names are usually named in CamelCase or snake_case (mostly C-style). Type name describes a single entity, i.e. if type name is in plural form it means a single entity represents multiple subentities.
```suggestion
enum ErrorCode {
```

2022-12-30 23:23 UTC, greye commented on test/test-viz.cpp
> +    SDL_INIT_FAILURE = -3
There is a convention to prefix related enumeration names.
If actual enum values are not important, we can omit them.
```suggestion
    ERROR_EMPTY_FILENAME = 1, // non-zero to indicate a failure, subsequent values are increments
    ERROR_PARSER_FAILURE,
    ERROR_SDL_INIT_FAILURE
```

2022-12-30 23:23 UTC, greye commented on test/test-viz.cpp
> +    SDL_FRect position;
Unfortunate naming: `position` is probably a coordinate, but the field is an actual rectangle with sizes etc.

2022-12-30 23:23 UTC, greye commented on test/test-viz.cpp
> +    }
`Vertex` is not actually required, the calculation is performed on rectangles.

2022-12-30 23:23 UTC, greye commented on test/test-viz.cpp
> +    }
Unfortunate naming: line is probably... well, a line, but this is calculated based on a rectangle bounds. Assuming there are 9 predefined rectangle coordinates (top, bottom, left, right, center, top-left, top-right, bottom-left, bottom-right), this is a right-to-left connection and could look like this:
```suggestion
    static Line rightToLeftLine(const SDL_FRect &src, const SDL_FRect &dst) {
        double x1, y1, x2, y2;
        getRight(src, x1, y1);
        getLeft(dst, x2, y2);
        return { x1, y1, x2, y2 };
    }
    
    static void getRight(const SDL_FRect &rect, double &x, double &y) {
        x = rect.x + rect.w;
        y = rect.y + rect.h / 2;
    }
    
    static void getLeft(const SDL_FRect &rect, double &x, double &y) {
        x = rect.x;
        y = rect.y + rect.h / 2;
    }

```

2022-12-30 23:23 UTC, greye commented on test/test-viz.cpp
> +class logic_scheme {
Inconsistent naming

2022-12-30 23:23 UTC, greye commented on test/test-viz.cpp
> +    void add_gate(std::vector<std::string> inputs, const std::string& output, const std::string& type) {
Passing a vector by value

2022-12-30 23:23 UTC, greye commented on test/test-viz.cpp
> +    bool connection_search(Vertex& element, const std::string& input) {
Why not just call it `connect` or `find_and_connect`? Search probably should not have side effects.

2022-12-30 23:23 UTC, greye commented on test/test-viz.cpp
> +    void queue_handling() {
Based on the comment the name probably should be `find_and_connect_overlaps`, but this is still too general and tells nothing about the purpose.

General rule: when a comment is required do describe a name, the name is bad.

2022-12-30 23:23 UTC, greye commented on test/test-viz.cpp
> +                        if(connection_search(scheme[i], std::get<1>(queue[j]))) {
Using `std::tuple` obstructs the meaning of the components: consider a dedicated struct with named fields or _at the very least_ named local variables or a structured binding[1].

1. https://en.cppreference.com/w/cpp/language/structured_binding

2022-12-30 23:23 UTC, greye commented on test/test-viz.cpp
> +    }
Method names are usually starts with verbs, e.g. `printOutput` or just `print`

2022-12-30 23:23 UTC, greye commented on test/test-viz.cpp
> +    }
Mixing `out` and `std::cout` at the same time.

2022-12-30 23:23 UTC, greye commented on test/test-viz.cpp
> +    std::vector<std::tuple<Vertex, std::string>> queue;
`std::vector` is still a bad choice for queues using nested data structures: use vector of pointers at least.

2022-12-30 23:23 UTC, greye commented on test/test-viz.cpp
> +void setPosition(std::vector<Vertex*> elements, const int max_elements, const float height, const float width, const int screen_height) {
Passing an `std::vector` by value

2022-12-30 23:23 UTC, greye commented on test/test-viz.cpp
> +    for(int& input : element->ins) {
Do not iterate by non-const reference when mutation is not required: iterate by value for primitive types and by const-reference for structures.

2022-12-30 23:23 UTC, greye commented on test/test-viz.cpp
> +void setConnections(Vertex* element, const std::vector<Vertex>& scheme, std::vector<Line>& connections) {
Why passing an `element` by non-const pointer? Why not const-reference?

2022-12-30 23:23 UTC, greye commented on test/test-viz.cpp
> +    std::cin >> filename;
It is generally preferred for simple applications to pass arguments via CLI, i.e. `argv`

2022-12-30 23:23 UTC, greye commented on test/test-viz.cpp
> +        std::cout << "Empty filename\n";
Error and debug messages should be logged to `std::cerr`.

2022-12-30 23:23 UTC, greye commented on test/test-viz.cpp
> +
Declare variables as close as possible to the point of use, init variables immediately with target values, e.g.
```
SDL_DisplayMode displayMode;
SDL_GetCurrentDisplayMode(0, &displayMode);
```

2022-12-30 23:23 UTC, greye commented on test/test-viz.cpp
> +int main(int argc, char* argv[]) {
The current `main` implementation is overburdened and inconsequential. Now it boils down to the sequence:

1. Parse input
2. logicScheme.queue_handling();
3. logicScheme.output(std::cout);
4. Init SDL and create a window
5. Finding total number of layers in element with max layer
6. Sorting elements in order by layers
8. Finding the number of elements in layer with the most elements
9. calculate rect coords
10. calculate edge coords
11. draw
12. event loop
13. shutdown

Points 4 to 10 must be dedicated procedures, and `main` should be condensed and reordered to the following:

1. Parse input
2. Init SDL window
3. Prepare the draw data
4. Draw
5. Event loop
6. Shutdown

2022-12-31 12:07 UTC, yaksase commented on test/test-viz.cpp
> +    void add_gate(std::vector<std::string> inputs, const std::string& output, const std::string& type) {
It is needed to pass a vector by value to copy a const vector into a non-const vector to be able to erase the elements

2022-12-31 12:41 UTC, greye commented on test/test-viz.cpp
> +    void add_gate(std::vector<std::string> inputs, const std::string& output, const std::string& type) {
Why erasing at all? The line in question is 92: an item is erased when connection succeeds, then `i` is incremented in loop (effectively skipping `i + 1` btw), then all the inputs left are being added to the queue at 95-97. Why not just adding to the queue when connection fails?

2023-01-03 20:52 UTC, yaksase commented on test/test-viz.cpp
> +    std::vector< std::tuple< Vertex, std::vector< std::string > > > _queue;
would std::list be good for that?

2023-03-26 13:28 UTC, greye requested changes
- Format the code to adhere to the code style described in the https://github.com/mvg-internship/utopia-eda/blob/main/CODE_STYLE
- Restore deleted test files

2023-03-26 13:28 UTC, greye commented on src/main.cpp
> +const int screen_height = GetSystemMetrics(SM_CYSCREEN);
Get rid of Windows-specific APIs.

2023-03-26 13:28 UTC, greye commented on src/main.cpp
> +const char *parser_end_elem = "end_element";
`const char *` are mutable pointers to immutable data, you have better options for the task:
- `const char * const varname = ...`
- `const char varname[] = ...`
- `const std::string varname(...)`

2023-03-26 13:28 UTC, greye commented on src/main.cpp
> +    friend std::ostream &operator<<(std::ostream &out, const NormalizedElement &element_to_print);
`operator<<` overload does not have to be a `friend` since all `NormalizedElement` fields are public.

2023-04-01 08:26 UTC, greye requested changes

2023-04-01 08:26 UTC, greye commented on src/main.cpp
> +    std::vector<NormalizedElement> &elements_to_parse) {
```suggestion
int parseInput(
    const char *filename,
    std::vector<NormalizedElement> &elements_to_parse) {
```

2023-04-01 08:26 UTC, greye commented on src/main.cpp
> +    const NormalizedElement &element_to_print) {
```suggestion
std::ostream &operator<<(
    std::ostream &out,
    const NormalizedElement &element_to_print) {
```

2023-04-01 08:26 UTC, greye commented on src/main.cpp
> +    const int screen_h) {
```suggestion
void draw(
    SDL_Window *window,
    const std::vector<NormalizedElement> &elements_to_draw,
    const int screen_w,
    const int screen_h) {
```

2023-04-01 08:26 UTC, greye commented on test/CMakeLists.txt
Restore the provided sample

2023-04-01 08:26 UTC, greye commented on test/bench.cpp
Restore the provided sample

2023-04-01 08:26 UTC, greye commented on test/ttf_sample.cpp
Restore the provided sample

2023-04-01 08:26 UTC, greye commented on src/main.cpp
> +                                              SDL_RENDERER_ACCELERATED);
```suggestion
  SDL_Renderer *renderer =
      SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED);
```

2023-04-01 08:26 UTC, greye commented on src/main.cpp
> +                            normalizedToScreenY(n_connection.vertices[i].n_y, screen_h));
```suggestion
        SDL_RenderDrawLineF(
            renderer,
            normalizedToScreenX(n_connection.vertices[i - 1].n_x, screen_w),
            normalizedToScreenY(n_connection.vertices[i - 1].n_y, screen_h),
            normalizedToScreenX(n_connection.vertices[i].n_x, screen_w),
            normalizedToScreenY(n_connection.vertices[i].n_y, screen_h));
```

2023-04-01 08:26 UTC, greye commented on src/main.cpp
> +                                        SDL_WINDOW_SHOWN);
```suggestion
  SDL_Window *window =
      SDL_CreateWindow("test-viz", 0, 0, screen_w, screen_h, SDL_WINDOW_SHOWN);
```

2023-04-01 17:42 UTC, greye requested changes

2023-04-01 17:42 UTC, greye commented on src/main.cpp
> +  element_to_print.point.n_y << std::endl;
Consider formatting multi-line statements:
```suggestion
  out << "Element id: " << element_to_print.id
      << " x: " <<  element_to_print.point.n_x
      << " y: " <<  element_to_print.point.n_y
      << std::endl;
```

2023-04-01 17:42 UTC, greye commented on src/main.cpp
> +  SDL_CreateWindow("test-viz", 0, 0, screen_w, screen_h, SDL_WINDOW_SHOWN);
```suggestion
  SDL_Window *window = 
      SDL_CreateWindow("test-viz", 0, 0, screen_w, screen_h, SDL_WINDOW_SHOWN);
```

2023-04-01 17:42 UTC, greye commented on src/main.cpp
> +      connection.vertices[i].n_y;
```suggestion
      out << " x" << i << ": " << connection.vertices[i].n_x
          << " y" << i << ": " << connection.vertices[i].n_y;
```

2023-04-02 18:34 UTC, merged